apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: eks-local-disk-provisioner
  labels:
    app: eks-local-disk-provisioner
spec:
  template:
    metadata:
      labels:
        name: eks-local-disk-provisioner
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
      - name: eks-local-disk-provisioner
        image: ethersphere/eks-local-disk-provisioner:latest
        imagePullPolicy: Always
        env:
          - name: PARTED_SCRIPT
            value: "mklabel gpt mkpart logical 0% 50% mkpart logical 50% 100%"
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-dev
            mountPath: /dev
            mountPropagation: "Bidirectional"
          - name: host-disks
            mountPath: /mnt/disks
            mountPropagation: "Bidirectional"
          - name: host-etc-fstab
            mountPath: /etc/fstab
            subPath: fstab
            mountPropagation: "Bidirectional"
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-disks
          hostPath:
            path: /mnt/disks
        - name: host-etc-fstab
          hostPath:
            path: /etc
      nodeSelector:
        eks-local-disk-provisioner: "true"
