apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: development
spec:
  # Add fields here
  size: 2
  image: aerospike/aerospike-server-enterprise:5.7.0.8

  # When defining storage both the data volume defined here as nsvol1 and the
  # workdir volume.  AKO requires a workdir volume or the pods won't mount.
  # mount path for the data volume should match to the LVP mounts
  # or at least I like to keep it that way.
  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    blockVolumePolicy:
      cascadeDelete: true
    volumes:
      - name: workdir
        aerospike:
          path: /opt/aerospike
        source:
          persistentVolume:
            storageClass: local-path
            volumeMode: Filesystem
            size: 5Gi
      - name: nsvol1
        aerospike:
          path: /data
        source:
          persistentVolume:
            storageClass: local-path
            volumeMode: Filesystem
            size: 60Gi

      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

#  podSpec:
#    multiPodPerHost: true
  podSpec:
    # Because you are using local volumes you probably don't want multiple hosts
    multiPodPerHost: false
    # We need to expose the AS cluster to the outside world through the host
    # network
    hostNetwork: false
    # CRITICAL
    # You must define a podAntiAffinity rule or the pod will have no idea where to
    # put itself and the K8s secheduler won't schedule the pod.
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - aerospike-cluster
          topologyKey: kubernetes.io/hostname

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security: {}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        memory-size: 5000000000
        replication-factor: 2
        storage-engine:
          type: device
          files:
            - /data/small.dat
          filesize: 60000000000
          data-in-memory: true
            # - /mnt/disks/data
            # #- /dev/nvme0n1

  seedsFinderServices:
    loadBalancer:
      externalTrafficPolicy: Local
      annotations:
        app: "aerospike"
        role: "seed_finder_services"
