apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "local-ssd"
provisioner: "kubernetes.io/no-provisioner"
volumeBindingMode: "WaitForFirstConsumer"
# Setting the volumeBindingMode to WaitForFirstConsumer is criticate
# if you set it to Immediate it will try to bind before the pod affinity rules
# are fully exercised
