kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/mnt/disks"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu

    export
    echo "------"
    echo "VOL_DIR: $VOL_DIR"
    echo "VOL_MODE: $VOL_MODE"
    echo "VOL_SIZE_BYTES: $VOL_SIZE_BYTES"

    mkdir -m 0777 -p "$VOL_DIR"
    str1="$VOL_MODE"
    str2="Filesystem"
    if [[ $str1 = $str2 ]]
    then
     mkdir $VOL_DIR/data
     touch $VOL_DIR/data/small.dat
    fi

  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
