apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: eks-nvme-ssd-provisioner
  labels:
    app: eks-nvme-ssd-provisioner
spec:
  selector:
    matchLabels:
      name: eks-nvme-ssd-provisioner
  template:
    metadata:
      labels:
        name: eks-nvme-ssd-provisioner
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        aws.amazon.com/eks-local-ssd: "true"
      priorityClassName: system-node-critical
      containers:
      - name: eks-nvme-ssd-provisioner
        image: oscarmherrera/eks-nvme-ssd-provisioner:latest
        imagePullPolicy: Always
        env:
          - name: PARTED_SCRIPT
            value: ""mklabel gpt mkpart logical 0% 80% mkpart logical 20% 100%""
          - name: RAW_DEVICE
            value: "1"
          - name: BASE_DIR
            value: /pv-disks
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /pv-disks
            name: pv-disks
            mountPropagation: "Bidirectional"
          - mountPath: /nvme
            name: nvme
            mountPropagation: "Bidirectional"
      volumes:
      - name: pv-disks
        hostPath:
          path: /pv-disks
      - name: nvme
        hostPath:
          path: /nvme
